# Generated by Django 4.2.1 on 2023-05-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_servicearea_applications_alter_link_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the project', max_length=250)),
                ('organization', models.ManyToManyField(blank=True, to='app.organization')),
            ],
        ),
        migrations.RemoveField(
            model_name='application',
            name='region',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.AddField(
            model_name='application',
            name='project',
            field=models.ManyToManyField(blank=True, to='app.project'),
        ),
    ]
